main.pas
utils.pas

This fixes an error message that appears on Linux and possibly other posix systems when Trying to open a mapped directory. A message appears saying "Unable to execute <path>". This fixes it. 
The fix is not mine, but I googlecode is closed and I can't remember the name of the person who posted it.

Fix cannot execute on open (nix)

---

main.lfm

This VarGrid is shown in weird size on my computer when resizing the main window or PageInfo panel.
Here are two lines to give the label and the vargrid a fixed position.

Fix "Global Statistics" shown problem

---

transgui.lpr

I use transmisson-remote-gui on Arch Linux. A month ago, I manually built v5.6.0, but noticed that the tray icon was "empty": on execution, an icon in the tray was created, and worked successfully, but it did show as an empty square, not showing the png icon.
I have had a look at the code, and it seems that the resource file was only being included when building on Windows systems.
This pull request should re-add the resource file to all builds (at least, on my system, the icon shows again).

Missing Icon

---

synapse/source/lib/ssl_openssl_lib.pas

@PeterDaveHello note about this [here](https://github.com/leonsoft-kras/transmisson-remote-gui/pull/966/commits/9bba34167746ecc0108071f0a5d29dc62ebf1f66#r125749430).

ssl_openssl_lib.pas: Fixed copy-paste mistake.

---

setup/macosx/compilers.sh

Upgrade Lazarus to v1.8.0 & Free Pascal to v3.0.4 on macOS

---

readme.txt

Current link still points to Google Code which is very much deprecated / dead.

[Docs] Update `Project home` link

---

main.lfm
main.pas
rpc.pas

Add "private" column -- Reflects key-value pair "private=1" or "private=0" in the "info" dict of the torrent's metainfo file
Not tested for 5.14, It should work fine.
Fully tested for transmission cfp fork here -->https://github.com/cfpp2p/transmisson-remote-gui/commit/5721cfabbe487108dae604380d64c63e2d0a8857

Add "private" column

---

connoptions.lfm
connoptions.pas
main.pas
options.lfm

Add support for client certificates on non-windows machines

Client certificate

---

transgui.lpi

This change is kind of necessary for the Cocoa build unless certain references to the macOS framework headers are removed from transgui. Otherwise, there is a dependency on Carbon that cannot be resolved in the x86_64 macOS world, causing problems during compilation. See https://wiki.freepascal.org/univint
These flags enable smart linking, which causes anything that isn't used to be dropped at compile-time. Importantly, that includes the Carbon dependency when compiling for Cocoa.
I don't know how to figure out exactly what would need to be removed to get rid of the Carbon dependency, so this was the easier solution. Since it affects the other builds, at the request of @PeterDaveHello, I have separated it into its own pull request. In theory, this shouldn't break anything, but it …

Enable smart linking

---

main.lfm
main.pas
rpc.pas

This is for #978 
Functionality is explained in screenshot here https://github.com/transmission-remote-gui/transgui/issues/978#issuecomment-455859269
Ideally labels would have better UI with auto-complete and editing them would not be just a text field but something fancier with label bubbles and (x) buttons to remove them, kind of like issue tags work in gitlab. 
But this initial implementation is good enough to start using labels.
Note, you need dev build of transmission-daemon to test this. If labels are not supported by daemon their editing actions are disabled.

Initial support for labels

---

StringToVK.pas
about.lfm
about.pas
addlink.pas
addtorrent.pas
addtracker.pas
baseform.pas
bencode.pas
colsetup.pas
connoptions.pas
daemonoptions.pas
download.pas
ipresolver.pas
main.pas
movetorrent.pas
options.pas
passwcon.pas
readme.txt
restranslator.pas
rpc.pas
torrprops.pas
transgui.lpr
urllistenerosx.pas
utils.pas
vargrid.pas
varlist.pas

As requested by maintainers in issue #1239 
Added the OpenSSL exception to the copyright header, and added a copyright header to some files that was missing one. This sort of change should be done by the copyright holder(s), but since Transgui has been linked to OpenSSL since day one I think it is safe to assume that this was mr Sidorov's intention.

Openssl exception

---

addtorrent.pas

Fixes #1270
Moves the DeleteDirs(0) call to the beginning of the try block, and re-sets ItemIndex in any situation a dir was deleted from the list (which unsets the currently selected item and sets the combobox text to an empty string).

Fix absolute path error

---

README.md

There's already a PR #1357 addressing the change from `caskroom/cask` to `homebrew/cask`. But now that `caskroom` is essentially a [part](https://github.com/Homebrew/homebrew-cask) of Homebrew, we can streamline the installation process to one line. It will also work without the `--cask` option, but I intentionally left it in to indicate that it's a cask.

Update README.md (Homebrew: one-line installation)

---

synapse/source/lib/httpsend.pas

Adds transmission-remote-gui specific user-agent and bump default HTTP protocol to HTTP/1.1

Update user-agent and set default protocol to HTTP/1.1

---

rpc.pas

This is a more correct way to solve the problem described in #1325.
Any duplicate fields are removed.

Deduplicate RequestInfo params. 

---

.travis.yml

The project has been archived and is now read-only
Reference: https://github.com/bluzi/travis-buddy

Remove TravisBuddy integration as it's deprecated

---

rpc.pas

We now ask Transmission to use gzip to compress the payload before sending it to us. The savings are quite significant, as a torrent-get which is 2436 KiB in plain text is compressed to just 215 KiB.
FPC includes a Pascal implementation of zlib so this comes with no extra dependencies in the final binary.

Implement support for gzip-compressed HTTP payloads

---

rpc.pas

The `labels` field in `torrent-get` was added in Transmission 3.0, whose RPC version is 16.
We request this field unconditionally, which breaks Reflection. I'm not sure how pre-3.0 Transmission behave when they receive an unsupported field, but we have a lot of these checks anyway already so it just makes sense do to it for this one as well.

Don't request labels if running with pre-3.0 Transmission

---

synapse/source/lib/httpsend.pas

The `FSock.PreferIP4` setting is set to `True` which forces IPv4 only requests.
Setting it to true makes it use IPv6 but in IPv4 only clients this breaks the connectivity.
Therefore some type of IPv6 connectivity check is needed, ~which I used pinging to a the Cloudflare DNS IPv6 address with a timeout to set the setting.~
~In Linux this will only work with a sudo user as ping check needs sudo privileges on Linux.~
Best option to solve this is to implement Happy Eyeballs.
related: #1362
may be related: #1353, #485

Adds IPv6 support for HTTP requests

---

.travis.yml

Node.js v10 is EoL-ed for a while (since 2021-04-30), would be great to update to the a newer LTS version.
As node.js v18 prebuilt binary needs newer build environment, otherwise will receive the following error:
> node: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by node)
So just update to v16 first, and update to a new version later, after the build environment on Travis CI also updated to a new version.
Reference: https://github.com/nodejs/Release

Update node.js on Travis CI from dated v10 to v16

---

daemonoptions.pas
main.pas

A lot of places in transgui use integers in RPC requests where the daemon expects booleans.
A recent commit in Transmission started actually enforcing this as the JSON parsing implementation has changed.
Originally reported in https://github.com/xavery/transgui/issues/79 and cherry-picked from https://github.com/xavery/transgui/commit/409512f85001d0865dba2a21ce1497b2c60c0d8d.

Don't use integers in place of booleans in RPC
